# Generated by Django 5.1.7 on 2025-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='source_task',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='target_task',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='link',
            name='source_state',
        ),
        migrations.RemoveField(
            model_name='link',
            name='target_state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
